version: '3.8'

services:
  postgres:
    image:  postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bigdata_spark
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./исходные данные:/data/source_data
      - ./001-init_db.sql:/docker-entrypoint-initdb.d/001-init_db.sql
      - ./002-ddl.sql:/docker-entrypoint-initdb.d/002_ddl.sql

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DB: default
    ports:
      - "8123:8123"
      - "9000:9000"

  pyspark:
    image: jupyter/pyspark-notebook:latest
    container_name: pyspark
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - postgres
      - clickhouse

volumes:
  postgres_data: